services:
  caddy:
    image: caddy:2.7
    ports:
      - 2000:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  planera-api:
    image: planera-api
    environment:
      PLANERA_FRONTENDURL: http://localhost:2000
      PLANERA_EMAILCONFIRMATION: false
      PLANERA_SMTP__HOST: mx.example.org
      PLANERA_SMTP__PORT: 587
      PLANERA_SMTP__USER: user
      PLANERA_SMTP__PASSWORD: password
      PLANERA_SMTP__SENDER: noreply@example.org
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./data:/app/data
  planera-web:
    image: planera-web
    environment:
      ORIGIN: http://localhost:2000
    build:
      context: .
      dockerfile: web/Dockerfile