services:
  caddy:
    image: caddy:2.7
    privileged: true
    ports:
      - 2000:2000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  db:
    image: postgres:latest
    privileged: true
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 30
    environment:
      POSTGRES_USER: planera
      POSTGRES_PASSWORD: planera
      POSTGRES_DB: planera
    volumes:
      - ./data/db:/var/lib/postgresql/data
  planera-api:
    image: planera-api
    privileged: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      PLANERA_FRONTENDURL: https://localhost:2000
      PLANERA_EMAILCONFIRMATION: "false"
      PLANERA_POSTGRES__HOST: "db:5432"
      PLANERA_POSTGRES__USER: planera
      PLANERA_POSTGRES__PASSWORD: planera
      PLANERA_POSTGRES__DB: planera
      PLANERA_SMTP__HOST: mx.example.org
      PLANERA_SMTP__PORT: 587
      PLANERA_SMTP__USER: user
      PLANERA_SMTP__PASSWORD: password
      PLANERA_SMTP__SENDER: noreply@example.org
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./data/api:/app/data
  planera-web:
    image: planera-web
    environment:
      ORIGIN: https://localhost:2000
      VITE_PUBLIC_API_URL: https://localhost:2000/api
    build:
      context: .
      dockerfile: web/Dockerfile
