import type {EditorThemeClasses} from 'svelte-lexical';

import './taskEditorTheme.css';

const theme: EditorThemeClasses = {
    blockCursor: 'TaskEditorTheme__blockCursor',
    characterLimit: 'TaskEditorTheme__characterLimit',
    code: 'TaskEditorTheme__code',
    codeHighlight: {
        atrule: 'TaskEditorTheme__tokenAttr',
        attr: 'TaskEditorTheme__tokenAttr',
        boolean: 'TaskEditorTheme__tokenProperty',
        builtin: 'TaskEditorTheme__tokenSelector',
        cdata: 'TaskEditorTheme__tokenComment',
        char: 'TaskEditorTheme__tokenSelector',
        class: 'TaskEditorTheme__tokenFunction',
        'class-name': 'TaskEditorTheme__tokenFunction',
        comment: 'TaskEditorTheme__tokenComment',
        constant: 'TaskEditorTheme__tokenProperty',
        deleted: 'TaskEditorTheme__tokenProperty',
        doctype: 'TaskEditorTheme__tokenComment',
        entity: 'TaskEditorTheme__tokenOperator',
        function: 'TaskEditorTheme__tokenFunction',
        important: 'TaskEditorTheme__tokenVariable',
        inserted: 'TaskEditorTheme__tokenSelector',
        keyword: 'TaskEditorTheme__tokenAttr',
        namespace: 'TaskEditorTheme__tokenVariable',
        number: 'TaskEditorTheme__tokenProperty',
        operator: 'TaskEditorTheme__tokenOperator',
        prolog: 'TaskEditorTheme__tokenComment',
        property: 'TaskEditorTheme__tokenProperty',
        punctuation: 'TaskEditorTheme__tokenPunctuation',
        regex: 'TaskEditorTheme__tokenVariable',
        selector: 'TaskEditorTheme__tokenSelector',
        string: 'TaskEditorTheme__tokenSelector',
        symbol: 'TaskEditorTheme__tokenProperty',
        tag: 'TaskEditorTheme__tokenProperty',
        url: 'TaskEditorTheme__tokenOperator',
        variable: 'TaskEditorTheme__tokenVariable',
    },
    embedBlock: {
        base: 'TaskEditorTheme__embedBlock',
        focus: 'TaskEditorTheme__embedBlockFocus',
    },
    hashtag: 'TaskEditorTheme__hashtag',
    heading: {
        h1: 'TaskEditorTheme__h1',
        h2: 'TaskEditorTheme__h2',
        h3: 'TaskEditorTheme__h3',
        h4: 'TaskEditorTheme__h4',
        h5: 'TaskEditorTheme__h5',
        h6: 'TaskEditorTheme__h6',
    },
    image: 'editor-image',
    indent: 'TaskEditorTheme__indent',
    link: 'TaskEditorTheme__link',
    list: {
        listitem: 'TaskEditorTheme__listItem',
        listitemChecked: 'TaskEditorTheme__listItemChecked',
        listitemUnchecked: 'TaskEditorTheme__listItemUnchecked',
        nested: {
            listitem: 'TaskEditorTheme__nestedListItem',
        },
        olDepth: [
            'TaskEditorTheme__ol1',
            'TaskEditorTheme__ol2',
            'TaskEditorTheme__ol3',
            'TaskEditorTheme__ol4',
            'TaskEditorTheme__ol5',
        ],
        ul: 'TaskEditorTheme__ul',
    },
    ltr: 'TaskEditorTheme__ltr',
    mark: 'TaskEditorTheme__mark',
    markOverlap: 'TaskEditorTheme__markOverlap',
    paragraph: 'TaskEditorTheme__paragraph',
    quote: 'TaskEditorTheme__quote',
    rtl: 'TaskEditorTheme__rtl',
    table: 'TaskEditorTheme__table',
    tableAddColumns: 'TaskEditorTheme__tableAddColumns',
    tableAddRows: 'TaskEditorTheme__tableAddRows',
    tableCell: 'TaskEditorTheme__tableCell',
    tableCellActionButton: 'TaskEditorTheme__tableCellActionButton',
    tableCellActionButtonContainer:
        'TaskEditorTheme__tableCellActionButtonContainer',
    tableCellEditing: 'TaskEditorTheme__tableCellEditing',
    tableCellHeader: 'TaskEditorTheme__tableCellHeader',
    tableCellPrimarySelected: 'TaskEditorTheme__tableCellPrimarySelected',
    tableCellResizer: 'TaskEditorTheme__tableCellResizer',
    tableCellSelected: 'TaskEditorTheme__tableCellSelected',
    tableCellSortedIndicator: 'TaskEditorTheme__tableCellSortedIndicator',
    tableResizeRuler: 'TaskEditorTheme__tableCellResizeRuler',
    tableSelected: 'TaskEditorTheme__tableSelected',
    text: {
        bold: 'TaskEditorTheme__textBold',
        code: 'TaskEditorTheme__textCode',
        italic: 'TaskEditorTheme__textItalic',
        strikethrough: 'TaskEditorTheme__textStrikethrough',
        subscript: 'TaskEditorTheme__textSubscript',
        superscript: 'TaskEditorTheme__textSuperscript',
        underline: 'TaskEditorTheme__textUnderline',
        underlineStrikethrough: 'TaskEditorTheme__textUnderlineStrikethrough',
    },
};

export default theme;