import type {EditorThemeClasses} from "@paddim8/svelte-lexical";

import "./ticketEditorTheme.css";

export default {
    blockCursor: "TicketEditorTheme__blockCursor",
    characterLimit: "TicketEditorTheme__characterLimit",
    code: "TicketEditorTheme__code",
    codeHighlight: {
        atrule: "TicketEditorTheme__tokenAttr",
        attr: "TicketEditorTheme__tokenAttr",
        boolean: "TicketEditorTheme__tokenProperty",
        builtin: "TicketEditorTheme__tokenSelector",
        cdata: "TicketEditorTheme__tokenComment",
        char: "TicketEditorTheme__tokenSelector",
        class: "TicketEditorTheme__tokenFunction",
        "class-name": "TicketEditorTheme__tokenFunction",
        comment: "TicketEditorTheme__tokenComment",
        constant: "TicketEditorTheme__tokenProperty",
        deleted: "TicketEditorTheme__tokenProperty",
        doctype: "TicketEditorTheme__tokenComment",
        entity: "TicketEditorTheme__tokenOperator",
        function: "TicketEditorTheme__tokenFunction",
        important: "TicketEditorTheme__tokenVariable",
        inserted: "TicketEditorTheme__tokenSelector",
        keyword: "TicketEditorTheme__tokenAttr",
        namespace: "TicketEditorTheme__tokenVariable",
        number: "TicketEditorTheme__tokenProperty",
        operator: "TicketEditorTheme__tokenOperator",
        prolog: "TicketEditorTheme__tokenComment",
        property: "TicketEditorTheme__tokenProperty",
        punctuation: "TicketEditorTheme__tokenPunctuation",
        regex: "TicketEditorTheme__tokenVariable",
        selector: "TicketEditorTheme__tokenSelector",
        string: "TicketEditorTheme__tokenSelector",
        symbol: "TicketEditorTheme__tokenProperty",
        tag: "TicketEditorTheme__tokenProperty",
        url: "TicketEditorTheme__tokenOperator",
        variable: "TicketEditorTheme__tokenVariable",
    },
    embedBlock: {
        base: "TicketEditorTheme__embedBlock",
        focus: "TicketEditorTheme__embedBlockFocus",
    },
    hashtag: "TicketEditorTheme__hashtag",
    heading: {
        h1: "TicketEditorTheme__h1",
        h2: "TicketEditorTheme__h2",
        h3: "TicketEditorTheme__h3",
        h4: "TicketEditorTheme__h4",
        h5: "TicketEditorTheme__h5",
        h6: "TicketEditorTheme__h6",
    },
    image: "editor-image",
    indent: "TicketEditorTheme__indent",
    link: "TicketEditorTheme__link",
    list: {
        listitem: "TicketEditorTheme__listItem",
        listitemChecked: "TicketEditorTheme__listItemChecked",
        listitemUnchecked: "TicketEditorTheme__listItemUnchecked",
        nested: {
            listitem: "TicketEditorTheme__nestedListItem",
        },
        olDepth: [
            "TicketEditorTheme__ol1",
            "TicketEditorTheme__ol2",
            "TicketEditorTheme__ol3",
            "TicketEditorTheme__ol4",
            "TicketEditorTheme__ol5",
        ],
        ul: "TicketEditorTheme__ul",
    },
    ltr: "TicketEditorTheme__ltr",
    mark: "TicketEditorTheme__mark",
    markOverlap: "TicketEditorTheme__markOverlap",
    paragraph: "TicketEditorTheme__paragraph",
    quote: "TicketEditorTheme__quote",
    rtl: "TicketEditorTheme__rtl",
    table: "TicketEditorTheme__table",
    tableAddColumns: "TicketEditorTheme__tableAddColumns",
    tableAddRows: "TicketEditorTheme__tableAddRows",
    tableCell: "TicketEditorTheme__tableCell",
    tableCellActionButton: "TicketEditorTheme__tableCellActionButton",
    tableCellActionButtonContainer:
        "TicketEditorTheme__tableCellActionButtonContainer",
    tableCellEditing: "TicketEditorTheme__tableCellEditing",
    tableCellHeader: "TicketEditorTheme__tableCellHeader",
    tableCellPrimarySelected: "TicketEditorTheme__tableCellPrimarySelected",
    tableCellResizer: "TicketEditorTheme__tableCellResizer",
    tableCellSelected: "TicketEditorTheme__tableCellSelected",
    tableCellSortedIndicator: "TicketEditorTheme__tableCellSortedIndicator",
    tableResizeRuler: "TicketEditorTheme__tableCellResizeRuler",
    tableSelected: "TicketEditorTheme__tableSelected",
    text: {
        bold: "TicketEditorTheme__textBold",
        code: "TicketEditorTheme__textCode",
        italic: "TicketEditorTheme__textItalic",
        strikethrough: "TicketEditorTheme__textStrikethrough",
        subscript: "TicketEditorTheme__textSubscript",
        superscript: "TicketEditorTheme__textSuperscript",
        underline: "TicketEditorTheme__textUnderline",
        underlineStrikethrough: "TicketEditorTheme__textUnderlineStrikethrough",
    },
} as EditorThemeClasses;